database:
  host: ""  # хост
  user: ""  # имя пользователя
  passwd: ""  # пароль от базы данных
  db: ""  # название базы данных
user:
  user_token: ""  # Ваш токен
group:
  group_id: ""  # id группы
  group_token: ""  # Токен группы
app:
  app_token: ""  # Токен приложения
youtube:
  api_keys: ""  # Ключи для доступа к YouTube API, через запятую